apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: grafana-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
    - host: "grafana.santosops.com"
      http:
        paths:
          - backend:
              service:
                name: "grafana"
                port:
                  number: 3000
            pathType: "Prefix"
  tls:
    - hosts:
        - "grafana.santosops.com"
      secretName: "santos-ops"